#!/usr/bin/env bash

cat  << EOF
LOGIN_URL=${LOGIN_URL_UAT}
GRAPHQL_URL=${GRAPHQL_URL_UAT}
TALENT_CENTER_CLIENT_ID=${TALENT_CENTER_CLIENT_ID}
TALENT_CENTER_CLIENT_SECRET=${TALENT_CENTER_CLIENT_SECRET}
EOF
